services:
  felipe-medeiros-curriculo:
    image: felipe-medeiros-curriculo
    container_name: felipe-medeiros-curriculo
    build: .
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web: 
    name: web
    driver: bridge
  
    