services:
  felipe-medeiros-curriculo:
    image: felipe-medeiros-curriculo
    container_name: felipe-medeiros-curriculo
    build: .
    ports:
      - "3000:3000"
    networks:
      - web
  
  nginx:
    image: nginx:alpine
    container_name: nginx-felipe-curriculo
    volumes:
      - ~/nginx/nginx.conf:/etc/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - felipe-medeiros-curriculo
    networks:
      - web

networks:
  web: 
    driver: bridge
  
    